### ISSUE TITLE
Feature request: remove '.' if passing empty 'pre' prefix

### ISSUE THREAD

**Issue by daem0ndev** [mirchow/release-version#1]
In my app, I want the build number in the semver format to be just a simple integer, because its being parsed and written as version codes in cordova.

I would love to use your package for managing the build number on TeamCity, however, its forcing me to prefix the build with a '.' character. I am suggesting that if you specify --pre '' (empty string) that it would not add the . separator. 

For example:
package.json has 2.1.5, if i run `release-version -b 100 --pre ''` I would like to get 2.1.5-100

If passing an empty value to --pre is not favorable, then we could instead do something like --no-prefix as a flag that will not prefix the build number at all.

Let me know what you think, I dont mind submitting a PR as well if its something you want to support.

**Comment by mirchow** [comment]
That is good idea. Thanks.
I have added the feature to the code. Please pull 1.0.1.
