### ISSUE TITLE
Now that we're using r for release and b for build meta data....

### ISSUE THREAD

**Issue by daem0ndev** [mirchow/release-version#4]
It seems like the pre/prefix option should be to prefix the pre-release version.

For example, you initially wrote this script so that -b 2 --pre rc would produce x.x.x-rc.2, and now we made it so -r is the option for pre-release version and -b is left for build metadata. The --pre option is still modifying the build meta data, when I think you want it to be for the pre-release version name.

This would mean you would do -r 2 --pre rc to produce x.x.x-rc.2, and additionally, passing -b option would add build meta data as per spec item 10, so that would add +(build) after the -rc.2.

Let me know if you are ok with this and I can submit another PR.

**Comment by daem0ndev** [comment]
Just went ahead and created the [Pull Request](https://github.com/mirchow/release-version/pull/5)

**Comment by mirchow** [comment]
You're too fast Asif. Let me take a look at this pr.

**Comment by mirchow** [comment]
I made the prerelease optional and pulled your request in.
